services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rentfilms
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/rentfilms
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_LIQUIBASE_URL: jdbc:postgresql://postgres:5432/rentfilms
      SPRING_LIQUIBASE_USER: postgres
      SPRING_LIQUIBASE_PASSWORD: postgres
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - postgres
    networks:
      - backend-network


  postgres:
    container_name: postgres
    image: postgres:18
    environment:
      POSTGRES_DB: rentfilms
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    command: >
      postgres
      -c shared_buffers=512MB
      -c work_mem=64MB
      -c max_connections=100
      -c log_min_duration_statement=500
    networks:
      - backend-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d rentfilms" ]
      interval: 5s
      retries: 5


networks:
  backend-network:
    driver: bridge